spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/reggie?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
mybaits-plus:
  type-aliases-package: com.suo.pagetest.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

reggie:
  path: D:\img\

